article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from . import view

urlpatterns = [
    path('', view.home, name='home'),
    path('article/', include('article.urls', namespace='article')),
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url='static/img/favicon.ico')),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class ArticlePost(models.Model):
    # 外键，是另一个表的主键。on_delete控制删除外键后本表的行为
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    # auto_now即为每次更新时写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # Django内部Meta类定义模型类的相关特性
    class Meta:
        # 返回记录结果集依照什么字段排序，前面加‘-’是倒序
        ordering = ('-created',)

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

article/views.py
import markdown
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User

from .forms import ArticlePostForm
from .models import ArticlePost
# Create your views here.

def article_list(request):
    articles = ArticlePost.objects.all()
    context = {}
    context['articles'] = articles
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    article.body = markdown.markdown(article.body,
        extensions=[
            # 缩写、表格等
            'markdown.extensions.extra',
            # 代码高亮
            'markdown.extensions.codehilite',
        ])
    context = {}
    context['article'] = article
    return render(request, 'article/detail.html', context)

def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写")

    else:
        article_post_form = ArticlePostForm()
        context = {}
        context['article_post_form'] = article_post_form
        return render(request, "article/create.html", context)

templates/article/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
写文章
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <!-- 标题和作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}</div>
        <!-- 正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
    </div>
</div>

{% endblock %}

templates/article/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    首页
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <div class="col-4 mb-4">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class ="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang='zh-cn'>
    
    <head>
        <meta charset='utf-8'>
        <title>{% block title %}{% endblock %}</title>
        <!-- 引入bootstrap的css文件 -->
        <link rel='stylesheet' href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'md_css/default.css' %}">
    </head>

    <body>
        <!-- 引入导航栏 -->
        {% include 'header.html' %}
        <!-- 预留具体页面的位置 -->
        {% block content %}{% endblock %}
        <!-- 引入注脚 -->
        {% include 'footer.html' %}
        <!-- bootstrap.js依赖jquery.js和popper.js -->
        <script src="{% static 'jquery/jquery.js' %}"></script>
        <script src="{% static 'popper/popper.js' %}"></script>
        <!-- bootstrap.js -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright; All right reserved.</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'article:article_list' %}">Solaris' Blog</a>

        <!-- 导航栏入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/home.html
<html>
    <head>
        <meta charset='utf-8' />
        <title>This is Solaris' home</title>
    </head>
    <body>
        <p>{{ text }}</p>
    </body>
</html>